# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.PositiveIntegerField(verbose_name='vk id')),
                ('estimated_members_count', models.PositiveIntegerField(null=True, verbose_name='estimated members count')),
                ('member_list', models.TextField(blank=True, null=True)),
                ('member_list_length', models.PositiveIntegerField(null=True, verbose_name='vk id')),
            ],
            options={
                'verbose_name': 'vk model',
                'verbose_name_plural': 'vk models',
            },
        ),
    ]
