# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20170129_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkRequestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_vk_id', models.PositiveIntegerField(verbose_name='start vk id')),
                ('stop_vk_id', models.PositiveIntegerField(verbose_name='stop vk id')),
                ('type', models.CharField(choices=[('ecmc', 'estimate communities member count'), ('rcml', 'request communities member list')], max_length=10)),
            ],
            options={
                'verbose_name': 'vk request task',
                'verbose_name_plural': 'vk request task',
            },
        ),
        migrations.AlterModelOptions(
            name='vkcommunity',
            options={'verbose_name': 'vk community', 'verbose_name_plural': 'vk communities'},
        ),
    ]
