# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20170129_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkrequesttask',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is done'),
        ),
    ]
